### ISSUE TITLE
Database Creation

### ISSUE THREAD

**Issue by jfpatino01** [ISIS3510-Seccion-3-Grupo-32/Backend#8]
The databases we will use can be explained in two categories. 

For the first ones we will need to get this data and define which categories are the most important. For example, this means data sourced from police report database, public safety databases, and other.

For the second we will have to define what inputs we want and the databases will be made accordingly.

The following are the types and the corresponding DB:

1. Structure based on available data
- Police Reports DB
- Crime Legal Information DB

2. We define the structure
- PQRS DB
- Performance DB
- Logs DB
- Users DB
- Analytics DB
- Itineraries DB

**Comment by JMarts32** [comment]
We are using firebase DataBase. Therefore, the creation of the DB's is not necessary anymore
